apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudwatch-mcp.fullname" . }}
  labels:
    {{- include "cloudwatch-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "cloudwatch-mcp.selectorLabels" . | nindent 4 }}
