apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-graph-engine.fullname" . }}
  labels:
    {{- include "service-graph-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range .Values.service.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "service-graph-engine.selectorLabels" . | nindent 4 }}
