{{- if and .Values.serviceAccount.create .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-mcp.fullname" . }}-cluster-role-binding
  labels:
    {{- include "k8s-mcp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-mcp.fullname" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-mcp.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
