{{- if or .Values.secrets.database .Values.secrets.api .Values.secrets.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-mcp.fullname" . }}-secrets
  labels:
    {{- include "prometheus-mcp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.database }}
  {{- range $key, $value := .Values.secrets.database }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.secrets.api }}
  {{- range $key, $value := .Values.secrets.api }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.secrets.external }}
  {{- range $key, $value := .Values.secrets.external }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }} 