{{- if .Values.global.gcpCredentials.content }}
apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obliq-sre-agent.labels" . | nindent 4 }}
type: Opaque
data:
  gcp.json: {{ .Values.global.gcpCredentials.content | b64enc | quote }}
{{- end }}
