{{/*
Global Secret with environment variables organized by sections
Only create if globalSecret.create.enabled is true AND existing.enabled is false
*/}}
{{- if and .Values.global.globalSecret.create.enabled (not .Values.global.globalSecret.existing.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.globalSecret.create.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obliq-sre-agent.labels" . | nindent 4 }}
type: Opaque
data:
  # Dynamic service URLs based on namespace
  NEO4J_URI: {{ include "obliq-sre-agent.neo4jUri" . | b64enc }}
  MONGODB_URI: {{ include "obliq-sre-agent.mongodbUri" . | b64enc }}
  ANOMALY_DETECTOR_URL: {{ include "obliq-sre-agent.anomalyDetectionUrl" . | b64enc }}
  INCIDENT_MANAGER_URL: {{ include "obliq-sre-agent.incidentManagerUrl" . | b64enc }}
  RCA_SERVICE_URL: {{ include "obliq-sre-agent.rcaAgentUrl" . | b64enc }}
  AUTO_REMEDIATION_URL: {{ include "obliq-sre-agent.autoRemediationUrl" . | b64enc }}
  ACTIVE_INVENTORY_URL: {{ include "obliq-sre-agent.activeInventoryUrl" . | b64enc }}
  AWS_MCP_SERVER_URL: {{ include "obliq-sre-agent.awsMcpUrl" . | b64enc }}
  K8S_SERVER_URL: {{ include "obliq-sre-agent.k8sMcpUrl" . | b64enc }}
  
  # Namespace information
  NAMESPACE: {{ include "obliq-sre-agent.namespace" . | b64enc }}
  
  # Common environment variables
  NODE_ENV: {{ .Values.global.env.common.NODE_ENV | default "not-set" | b64enc }}
  LOG_LEVEL: {{ .Values.global.env.common.LOG_LEVEL | default "not-set" | b64enc }}
  LOGURU_LEVEL: {{ .Values.global.env.common.LOGURU_LEVEL | default "not-set" | b64enc }}
  TZ: {{ .Values.global.env.common.TZ | default "not-set" | b64enc }}
  ENVIRONMENT: {{ .Values.global.env.common.ENVIRONMENT | default "not-set" | b64enc }}
  CLUSTER_NAME: {{ .Values.global.env.common.CLUSTER_NAME | default "not-set" | b64enc }}
  AUTOMATIC_EXECUTION_ENABLED: {{ .Values.global.env.common.AUTOMATIC_EXECUTION_ENABLED | default "not-set" | b64enc }}
  KUBECONFIG_FILE_PATH: {{ .Values.global.env.common.KUBECONFIG_FILE_PATH | default "not-set" | b64enc }}
  DEBUG: {{ .Values.global.env.common.DEBUG | default "not-set" | b64enc }}
  # SSL/TLS Configuration for internal service communication
  SSL_VERIFY: {{ .Values.global.env.common.SSL_VERIFY | default "not-set" | b64enc }}
  TLS_VERIFY: {{ .Values.global.env.common.TLS_VERIFY | default "not-set" | b64enc }}
  DISABLE_SSL_VERIFICATION: {{ .Values.global.env.common.DISABLE_SSL_VERIFICATION | default "not-set" | b64enc }}
  # PORT is service-specific and not included in global secrets
  
  # Backend Service Configuration
  DEFAULT_ADMIN_EMAIL: {{ .Values.global.env.backend.DEFAULT_ADMIN_EMAIL | default "not-set" | b64enc }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.global.env.backend.DEFAULT_ADMIN_PASSWORD | default "not-set" | b64enc }}
  
  # Database Configuration
  NEO4J_USER: {{ .Values.global.env.database.NEO4J_USER | default "not-set" | b64enc }}
  NEO4J_PASSWORD: {{ .Values.global.env.database.NEO4J_PASSWORD | default "not-set" | b64enc }}
  NEO4J_AUTH: {{ .Values.global.env.database.NEO4J_AUTH | default "not-set" | b64enc }}
  NEO4J_DATABASE: {{ .Values.global.env.database.NEO4J_DATABASE | default "not-set" | b64enc }}
  MONGO_ROOT_USERNAME: {{ .Values.global.env.database.MONGO_ROOT_USERNAME | default "not-set" | b64enc }}
  MONGO_ROOT_PASSWORD: {{ .Values.global.env.database.MONGO_ROOT_PASSWORD | default "not-set" | b64enc }}
  MONGODB_DATABASE: {{ .Values.global.env.database.MONGODB_DATABASE | default "not-set" | b64enc }}
  MONGODB_USERNAME: {{ .Values.global.env.database.MONGODB_USERNAME | default "not-set" | b64enc }}
  MONGODB_PASSWORD: {{ .Values.global.env.database.MONGODB_PASSWORD | default "not-set" | b64enc }}
  
  # AWS Configuration
  AWS_ROLE_ARN_AWS_MCP: {{ .Values.global.env.aws.AWS_ROLE_ARN_AWS_MCP | default "not-set" | b64enc }}
  AWS_ROLE_ARN_EC2_CLOUDWATCH_ALARMS: {{ .Values.global.env.aws.AWS_ROLE_ARN_EC2_CLOUDWATCH_ALARMS | default "not-set" | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.env.aws.AWS_ACCESS_KEY_ID | default "not-set" | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.env.aws.AWS_SECRET_ACCESS_KEY | default "not-set" | b64enc }}
  AWS_REGION: {{ .Values.global.env.aws.AWS_REGION | default "not-set" | b64enc }}
  AWS_MCP_USERNAME: {{ .Values.global.env.aws.AWS_MCP_USERNAME | default "not-set" | b64enc }}
  AWS_MCP_PASSWORD: {{ .Values.global.env.aws.AWS_MCP_PASSWORD | default "not-set" | b64enc }}
  AWS_WEB_IDENTITY_TOKEN_FILE: {{ .Values.global.env.aws.AWS_WEB_IDENTITY_TOKEN_FILE | default "not-set" | b64enc }}
  METRICS_SAMPLING_INTERVAL_SECONDS: {{ .Values.global.env.aws.METRICS_SAMPLING_INTERVAL_SECONDS | default "not-set" | b64enc }}
  
  # OpenAI Configuration
  OPENAI_API_KEY: {{ .Values.global.env.openai.OPENAI_API_KEY | default "not-set" | b64enc }}
  
  # Prometheus Configuration
  PROMETHEUS_URL: {{ .Values.global.env.prometheus.PROMETHEUS_URL | default "not-set" | b64enc }}
  PROMETHEUS_USER: {{ .Values.global.env.prometheus.PROMETHEUS_USER | default "not-set" | b64enc }}
  PROMETHEUS_PASSWORD: {{ .Values.global.env.prometheus.PROMETHEUS_PASSWORD | default "not-set" | b64enc }}
  PROMETHEUS_MCP_USERNAME: {{ .Values.global.env.prometheus.PROMETHEUS_MCP_USERNAME | default "not-set" | b64enc }}
  PROMETHEUS_MCP_PASSWORD: {{ .Values.global.env.prometheus.PROMETHEUS_MCP_PASSWORD | default "not-set" | b64enc }}
  
  # Loki Configuration
  LOKI_URL: {{ .Values.global.env.loki.LOKI_URL | default "not-set" | b64enc }}
  LOKI_TOKEN: {{ .Values.global.env.loki.LOKI_TOKEN | default "not-set" | b64enc }}
  LOKI_USERNAME: {{ .Values.global.env.loki.LOKI_USERNAME | default "not-set" | b64enc }}
  LOKI_PASSWORD: {{ .Values.global.env.loki.LOKI_PASSWORD | default "not-set" | b64enc }}
  
  # Jira Configuration
  JIRA_EMAIL: {{ .Values.global.env.jira.JIRA_EMAIL | default "not-set" | b64enc }}
  JIRA_API_TOKEN: {{ .Values.global.env.jira.JIRA_API_TOKEN | default "not-set" | b64enc }}
  JIRA_BASE_URL: {{ .Values.global.env.jira.JIRA_BASE_URL | default "not-set" | b64enc }}
  JIRA_PROJECT_KEY: {{ .Values.global.env.jira.JIRA_PROJECT_KEY | default "not-set" | b64enc }}
  JIRA_PAT: {{ .Values.global.env.jira.JIRA_PAT | default "not-set" | b64enc }}
  
  # Slack Configuration
  SLACK_WEBHOOK_URL: {{ .Values.global.env.slack.SLACK_WEBHOOK_URL | default "not-set" | b64enc }}
  SLACK_BOT_TOKEN: {{ .Values.global.env.slack.SLACK_BOT_TOKEN | default "not-set" | b64enc }}
  
  
  # MCP Server configurations
  MCP_SERVERS_AWS_EC2: {{ .Values.global.env.mcp.MCP_SERVERS_AWS_EC2 | default "not-set" | b64enc }}
  MCP_SERVERS_K8S: {{ .Values.global.env.mcp.MCP_SERVERS_K8S | default "not-set" | b64enc }}
  MCP_SERVERS_PROMETHEUS: {{ .Values.global.env.mcp.MCP_SERVERS_PROMETHEUS | default "not-set" | b64enc }}
  MCP_SERVERS_NEO4J: {{ .Values.global.env.mcp.MCP_SERVERS_NEO4J | default "not-set" | b64enc }}
  MCP_SERVERS_LOKI: {{ .Values.global.env.mcp.MCP_SERVERS_LOKI | default "not-set" | b64enc }}
  MCP_SERVERS_FULL: {{ .Values.global.env.mcp.MCP_SERVERS_FULL | default "not-set" | b64enc }}
  MCP_SERVERS: {{ .Values.global.env.mcp.MCP_SERVERS | default "not-set" | b64enc }}
  NEO4J_MCP_URL: {{ .Values.global.env.mcp.NEO4J_MCP_URL | default "not-set" | b64enc }}
  NEO4J_MCP_USERNAME: {{ .Values.global.env.mcp.NEO4J_MCP_USERNAME | default "not-set" | b64enc }}
  NEO4J_MCP_PASSWORD: {{ .Values.global.env.mcp.NEO4J_MCP_PASSWORD | default "not-set" | b64enc }}
  
  # Certificate Configuration (removed - configure cert-manager manually if needed)
  
  # Service Graph Engine Configuration
  APM_PROVIDER: {{ .Values.global.env.sg.APM_PROVIDER | default "not-set" | b64enc }}
  UPDATE_INTERVAL_SECONDS: {{ .Values.global.env.sg.UPDATE_INTERVAL_SECONDS | default "not-set" | toString | b64enc }}
  SG_APM_PROVIDER: {{ .Values.global.env.sg.SG_APM_PROVIDER | default "not-set" | b64enc }}
  SG_UPDATE_INTERVAL_SECONDS: {{ .Values.global.env.sg.SG_UPDATE_INTERVAL_SECONDS | default "not-set" | toString | b64enc }}
  DD_API_KEY: {{ .Values.global.env.sg.DD_API_KEY | default "not-set" | b64enc }}
  DD_APP_KEY: {{ .Values.global.env.sg.DD_APP_KEY | default "not-set" | b64enc }}
  DD_SITE: {{ .Values.global.env.sg.DD_SITE | default "not-set" | b64enc }}
  DD_ENVIRONMENTS: {{ .Values.global.env.sg.DD_ENVIRONMENTS | default "not-set" | b64enc }}
  
  # Kubernetes Configuration
  KUBECONFIG_CONTENT: {{ .Values.global.kubeconfig.content | default "not-set" | b64enc }}
  
  # Observability Configuration
  OTEL_COLLECTOR_ENDPOINT: {{ .Values.global.env.observability.OTEL_COLLECTOR_ENDPOINT | default "not-set" | b64enc }}
  OTEL_COLLECTOR_HTTP_ENDPOINT: {{ .Values.global.env.observability.OTEL_COLLECTOR_HTTP_ENDPOINT | default "not-set" | b64enc }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.env.observability.OTEL_EXPORTER_OTLP_ENDPOINT | default "not-set" | b64enc }}
  OTEL_EXPORTER_OTLP_INSECURE: {{ .Values.global.env.observability.OTEL_EXPORTER_OTLP_INSECURE | default "not-set" | b64enc }}
  
  # Certificate configuration removed - configure cert-manager manually if needed
{{- end }}
