{{- if .Values.global.kubeconfig.content }}
apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obliq-sre-agent.labels" . | nindent 4 }}
type: Opaque
data:
  config: {{ .Values.global.kubeconfig.content | b64enc | quote }}
{{- end }}
