apiVersion: v2
name: aws-mcp
description: A Helm chart for deploying the AWS MCP (Model Context Protocol) service with multiple environment variables
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - aws-mcp
  - aws
  - mcp
  - model-context-protocol
  - application
  - container
  - deployment
maintainers:
  - name: support@avesha.io
    email: support@avesha.io
home: https://avesha.io
sources:
  - https://github.com
icon: https://via.placeholder.com/150x150.png?text=AWSMCP
annotations:
  category: Application
  licenses: Apache-2.0 